/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * @param {Object} event
 * @base _page1_page
 * @returns {Boolean}
*/
_page1_page.prototype.onpageinit = function(event) {
	
};

/**
 * @param {Object} event
 * @base _page1_page
 * @returns {Boolean}
*/
_page1_page.prototype.button1_ontap = function(event) {
	pageManager.changePage("page2");
};

/**
 * @param {Object} event
 * @base _page1_page
 * @returns {Boolean}
*/
_page1_page.prototype.onpagecreate = function(event) {
	console.log("Page 1 is created");
};

/**
 * @param {Object} event
 * @base _page1_page
 * @returns {Boolean}
*/
_page1_page.prototype.listitem3_onswipeleft = function(event) {
	this.listitem3.remove();
};

