algoritmo "MENSAGEM NOME IDADE"
// Função :Mensagem informando nome e idade
// Autor :cleilson
// Data : 25/02/2016
// Seção de Declarações 
var
nome,idade:caractere
inicio
// Seção de Comandos

escreval("Digite seu nome ")
       leia(nome)
       
escreval("Informe sua idade")
       leia(idade)
       
       limpatela
       escreva("Seu nome é ",nome, " e você tem ",idade, " anos")
fimalgoritmo
