algoritmo "média"
// Função :calcular e mostrar a média dos 3 valores
// Autor :cleilson
// Data : 22/02/2016
// Seção de Declarações 
var
valor1,valor2,valor3,media:real
inicio
// Seção de Comandos
escreval("digite primeiro valor")
   leia(valor1)
   
escreval("digite segundo valor")
   leia(valor2)
   
escreval("digite terceiro valor")
    leia(valor3)
    
    limpatela
    media<-(valor1+valor2+valor3)/3
    escreva("A média dos três valores é",media)
    
fimalgoritmo
