algoritmo "Radiano do ângulo informado"
// Função :Conversão
// Autor :cleilson
// Data : 24/02/2016
// Seção de Declarações 
var
angulo,p,radiano:real
inicio
// Seção de Comandos 
escreval("digite um angulo em graus(g)")
      leia(angulo)
// A variavel p - corresponde ao valor de Pi
      p<-3.1416
                radiano<-(angulo*p)/180
                      escreva("o valor de conversão de ângulo para radiano é",radiano)


fimalgoritmo
