algoritmo "semnome"
// Função :
// Autor :
// Data : 25/02/2016
// Seção de Declarações 
var
vendedor:caractere
salario_fixo:real
vendas:real
salario_final:real
inicio
// Seção de Comandos 

escreva("Informe nome do vendedor = ")
leia(vendedor)
escreva("Salario fixo : ")
leia(salario_fixo)

// Valor de vendas do mês em dinheiro
escreva("Vendas do mês ")
leia(vendas)

salario_final<-((salario_fixo)+(vendas*15)/100))
     escreva("fim de mês",salario_final)

fimalgoritmo
