/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

// page class
/**
*  Object _page1_page()
*  @super _page
*  @constructor
*  @memberOf _page1_page 
*/
function _page1_page() {
}

//inherit _page
_page1_page.prototype = new _page("page1");

// widget assist
_page1_page.prototype.header1 = undefined;
_page1_page.prototype.content1 = undefined;
_page1_page.prototype.list1 = undefined;
_page1_page.prototype.listitem1 = undefined;
_page1_page.prototype.listitem2 = undefined;
_page1_page.prototype.listitem3 = undefined;
_page1_page.prototype.listitem4 = undefined;
_page1_page.prototype.listitem5 = undefined;

// default widget event handler

_page1_page.prototype.init_page = function(isStartPage, htmlPath, cssPath, managedCssPath) {
	this.htmlPath = htmlPath;
	this.cssPath = cssPath;
	this.managedCssPath = managedCssPath;
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.header1 = $("#page1 #header1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.content1 = $("#page1 #content1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.list1 = $("#page1 #list1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.listitem1 = $("#page1 #listitem1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.listitem2 = $("#page1 #listitem2");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.listitem3 = $("#page1 #listitem3");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.listitem4 = $("#page1 #listitem4");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.listitem5 = $("#page1 #listitem5");

		// bind widget event handler

	}, isStartPage);

};
