algoritmo "Sexo válido ou invalido "
// Função :Informar se a letra digitada corresponde a condição de informe de sexo valido - M ou F
// Autor :cleilson
// Data : 29/02/2016
// Seção de Declarações
var
sexo:caractere
inicio
// Seção de Comandos

escreval("Informe o sexo com uma letra válida")
leia(sexo)

se (sexo="m") OU (sexo="f") entao
   escreval("Sexo válido")
senao
   escreval("Sexo inválido")
fimse
   fimalgoritmo
