algoritmo "vogal e consoante"
// Função :escolha caso
// Autor :cleilson
// Data : 18/03/2016
// Seção de Declarações 
var
letra:caractere
inicio
// Seção de Comandos 

escreval("Escreva um letra para identifcação")
leia(letra)

escolha letra
caso "a","e","i","o","u"
     escreval("A letra informada é uma vogal")
outrocaso
         escreval("A letra informada é uma consoante")
fimescolha
fimalgoritmo
