Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação] 
// Professor    : Elidiane Martins 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2016
Var
// Seção de Declarações das variáveis 

num:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

num<-11

repita
      num<-(num-1)
      escreva(num)


ate num < 1


Fimalgoritmo