Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação] 
// Professor    : Elidiane Martins 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2016
Var
// Seção de Declarações das variáveis 

num:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

num<-10

enquanto num >=1 faca
         escreva(num)
         num<-num-1
fimenquanto



Fimalgoritmo