Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação] 
// Professor    : Elidiane Martins 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2016
Var
// Seção de Declarações das variáveis 

num,n:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("informe valor de n")
leia(n)

num<-1

repita
      escreva(num)
      num<-num+1

ate num>n



Fimalgoritmo